package exnihilocreatio.registries;

import exnihilocreatio.items.ore.ItemOre;
import exnihilocreatio.items.ore.Ore;
import exnihilocreatio.registries.manager.ExNihiloRegistryManager;
import exnihilocreatio.texturing.Color;
import exnihilocreatio.util.ItemInfo;

import java.util.HashSet;

@Deprecated
public class OreRegistry {
    /**
     * Registers a new custom piece, hunk, dust and potentially ingot to be
     * generated by Ex Nihilo Creatio.
     *
     * @param name  Unique name for ore
     * @param color Color for the pieces
     * @param info  Final result for the process. If null, an ingot is generated.
     *              Otherwise, the hunk will be smelted into this.
     * @return Ore, containing the base Ore object.
     */
    public static Ore register(String name, Color color, ItemInfo info) {
        return ExNihiloRegistryManager.ORE_REGISTRY.register(name, color, info);
    }

    @Deprecated
    public static HashSet<ItemOre> getItemOreRegistry() {
        return new HashSet<>(ExNihiloRegistryManager.ORE_REGISTRY.getItemOreRegistry());
    }
}
