package exnihilocreatio.registries.manager;

import exnihilocreatio.registries.registries.BarrelLiquidBlacklistRegistryNew;

public interface IBarrelLiquidBlacklistDefaultRegistryProvider extends IDefaultRecipeProvider<BarrelLiquidBlacklistRegistryNew> {
}
