package exnihilocreatio.registries.manager;

import exnihilocreatio.registries.registries.FluidBlockTransformerRegistryNew;

public interface IFluidBlockDefaultRegistryProvider extends IDefaultRecipeProvider<FluidBlockTransformerRegistryNew> {
}
