package exnihilocreatio.registries.manager;

import exnihilocreatio.registries.registries.FluidBlockTransformerRegistry;

public interface IFluidBlockDefaultRegistryProvider extends IDefaultRecipeProvider<FluidBlockTransformerRegistry> {
}
